FROM python:3.10-slim

# 필요한 패키지 설치
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libffi-dev nodejs jq vim maven lsof npm wget tar&& \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install fastapi uvicorn psutil python-multipart

ENV TZ="Asia/Seoul"

