apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: skala-practice
type: Opaque
data:
  username: dXNlcm5hbWU=    # Base64로 인코딩된 값 (예: "username")
  password: cGFzc3dvcmQ=    # Base64로 인코딩된 값 (예: "password")
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: skala-practice
data:
  app.properties: |
    app.name=MyApp
    app.version=1.0.0
    app.environment=production
  log.level: INFO
  max.connections: "100"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: skala-practice
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: efs-sc-shared

