apiVersion: apps/v1
kind: Deployment
metadata:
  name: skala-webserver
  namespace: skala-practice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skala-webserver
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
        prometheus.io/path: '/actuator/prometheus'
        update: 4c493b30222e66e1e53884c0e6bf5798
      labels:
        app: skala-webserver
    spec:
      serviceAccountName: default
      containers:
      - name: webserver
        image: amdp-registry.skala-ai.com/skala25a/skala-webserver:1.0.0
        imagePullPolicy: Always
        env:
        - name: LOGGING_LEVEL
          value: DEBUG
        - name: USER_NAME
          value: himang10
